### ISSUE TITLE
When used with aws-sdk-php functions.php file gets deleted

### ISSUE THREAD

**Issue by dingo-d** [BrianHenryIE/strauss#118]
I noticed when I used aws-sdk-php library in my projects, and when it gets prefixed with my custom prefix that the [`functions.php` file](https://github.com/aws/aws-sdk-php/blob/master/src/functions.php) from the lib gets deleted.

When I go to the `vendor-prefixed/aws/aws-sdk-php/src/functions.php` all I see is

```php
<?php // This file was deleted by {@see https://github.com/BrianHenryIE/strauss}.
```

am I missing something?

**Comment by BrianHenryIE** [comment]
Unable to reproduce, this passes:

```php
<?php
/**
 * `vendor-prefixed/aws/aws-sdk-php/src/functions.php` contains ~`This file was deleted by ... strauss`.
 *
 * @see https://github.com/BrianHenryIE/strauss/issues/118
 */

namespace BrianHenryIE\Strauss\Tests\Issues;

use BrianHenryIE\Strauss\Tests\Integration\Util\IntegrationTestCase;

/**
 * @package BrianHenryIE\Strauss\Tests\Issues
 * @coversNothing
 */
class StraussIssue118Test extends IntegrationTestCase
{
    public function test_file_contents_deleted()
    {

        $composerJsonString = <<<'EOD'
{
  "name": "issue/118",
  "require": {
    "aws/aws-sdk-php": "3.317"
  },
  "extra": {
    "strauss": {
      "namespace_prefix": "Company\\Project\\"
    },
    "aws/aws-sdk-php": [
        "S3"
    ]
  },
  "scripts": {
    "pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
  }
}
EOD;

        chdir($this->testsWorkingDir);

        file_put_contents($this->testsWorkingDir . '/composer.json', $composerJsonString);

        exec('composer install');

        $this->runStrauss();

        $php_string = file_get_contents($this->testsWorkingDir . '/vendor-prefixed/aws/aws-sdk-php/src/functions.php');

        self::assertStringNotContainsString('This file was deleted', $php_string);
        self::assertStringContainsString('// Functional functions', $php_string);
    }
}
```

It sounds like you're using `delete_vendor_files`. When that is `true`, if the files referenced in the `files` autoloader of the modified package are deleted, Composer's `autoload.php` will crash as it tries to open that file, so we replace it with an empty file. I'm not 100% sure this is the best way – we could delete it and then edit the Composer autoloader. I can't remember right now why this approach was chosen instead of modifying the autoloader in the `vendor/composer` directory.

I suspect you're actually looking at `vendor/aws/aws-sdk-php/src/functions.php` and `vendor-prefixed/aws/aws-sdk-php/src/functions.php` is correct.

Share a complete `composer.json` if it's truely a bug.

**Comment by dingo-d** [comment]
Yeah, it could be that. I had some weird behavior with this, sometimes it would be shown, and other times it would get deleted, but now it works, and I don't know what I did 😅 

Thanks for the explanation tho 🙂 👍🏼
