### ISSUE TITLE
`final` keyword prefixed with classmap prefix

### ISSUE THREAD

**Issue by Dartui** [BrianHenryIE/strauss#119]
# Problem

- download repository: https://github.com/Dartui/strauss-final-prefix
- run `composer install && composer prefix-namespaces` to replicate issue.
- go to `dependencies/symfony/polyfill-php80/Resources/stubs/Attribute.php` and see that class declaration has unwanted classmap prefix

<img width="509" alt="image" src="https://github.com/user-attachments/assets/00992f30-35a1-4812-9a5f-f89df31e1240">

I was able to narrow this error down to the `vendor/symfony/console/CHANGELOG.md` file which contains `class final`.

<img width="509" alt="image" src="https://github.com/user-attachments/assets/e7e58cd2-2400-41e4-b82d-bdd55d6cbe67">

`FileScanner@find` method regexp recognizes this as valid class name (I guess), adds it as class symbol and then uses it to replace word `final`.

# Solution

Simplest solution would be to scan only `.php` files for class discovery. Locally I did simple check that solved this issue, but I guess that for some reason scanning is not limited only to PHP files.

<img width="465" alt="image" src="https://github.com/user-attachments/assets/6827d08b-05d7-4054-ba9c-4095a03975ec">

**Comment by BrianHenryIE** [comment]
I don't think there was any intent to scan more than just PHP files, rather it hasn't been an issue until now.

There are potentially other file types that could have replacements made in them, e.g. the Authorize.net SDK uses (used?) a SOAP XML file and it parsed that to know what classes were used for which endpoints. It'd be nice to have but hasn't been an issue for me in years.

Thanks for the detailed report, very helpful.

Fixed with https://github.com/BrianHenryIE/strauss/compare/2e0a2f8beed433f7661ef498a1ea913b9b834956...d046e3ff1806251d68e456aafa24ae78b1d4a05c; released in [0.19.3](https://github.com/BrianHenryIE/strauss/releases/tag/0.19.3).
