### ISSUE TITLE
Package is not being installed

### ISSUE THREAD

**Issue by dingo-d** [BrianHenryIE/strauss#121]
I'm sending a MRE of the composer packages I'm trying to install for the plugin I'm working on:

```json
{
	"name": "test/test",
	"description": "Test",
	"type": "wordpress-plugin",
	"autoload": {
		"psr-4": {
			"SomePrefix\\": [
				"src/"
			]
		}
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "https://github.com/dingo-d/wp-sqlite-db"
		}
	],
	"require": {
		"php": ">8.2",
		"aws/aws-sdk-php": "^3.324.0",
		"woocommerce/action-scheduler": "^3.7"
	},
	"require-dev": {
		"dealerdirect/phpcodesniffer-composer-installer": "^1.0.0",
		"dingo-d/wp-pest": "^1.7.0",
		"php-parallel-lint/php-console-highlighter": "^1.0.0",
		"php-parallel-lint/php-parallel-lint": "^1.3.2",
		"php-stubs/woocommerce-stubs": "^9.1.0",
		"php-stubs/wordpress-stubs": "^6.6.2",
		"phpcompatibility/phpcompatibility-wp": "^2.1",
		"roave/security-advisories": "dev-latest",
		"squizlabs/php_codesniffer": "^3.0",
		"szepeviktor/phpstan-wordpress": "^v1.3.4"
	},
	"config": {
		"classmap-authoritative": true,
		"sort-packages": true,
		"optimize-autoloader": true,
		"process-timeout": 2000,
		"allow-plugins": {
			"dealerdirect/phpcodesniffer-composer-installer": true,
			"composer/installers": true,
			"pestphp/pest-plugin": true
		}
	},
	"scripts": {
		"test:types": "@php ./vendor/bin/phpstan analyze",
		"test:lint": "@php ./vendor/php-parallel-lint/php-parallel-lint/parallel-lint . -e php --show-deprecated --exclude vendor --exclude .git --exclude wp --exclude wp-content",
		"test:standards-check": "@php ./vendor/squizlabs/php_codesniffer/bin/phpcs",
		"test:unit": "@php ./vendor/bin/pest --group=unit",
		"test:integration": "@php ./vendor/bin/pest --group=integration",
		"test:integration-cov": "@php -dxdebug.mode=coverage ./vendor/bin/pest --group=integration --coverage",
		"test": [
			"@test:lint",
			"@test:types",
			"@test:standards-check",
			"@test:integration"
		],
		"prefix-namespaces": [
			"@php strauss.phar",
			"composer dump-autoload"
		],
		"post-install-cmd": [
			"@php strauss.phar",
			"composer dump-autoload"
		],
		"post-update-cmd": [
			"@php strauss.phar",
			"composer dump-autoload"
		]
	},
	"scripts-descriptions": {
		"test:types": "Run the PHPStan script against the entire codebase.",
		"test:lint": "Lint PHP files against parse errors.",
		"test:standards-check": "Run the PHPCS script against the entire codebase.",
		"test:unit": "Run wp-pest unit tests.",
		"test:integration": "Run wp-pest integration tests.",
		"test": "Run all checks (lint, phpstan, phpcs) and tests."
	},
	"extra": {
		"strauss": {
			"namespace_prefix": "SomePrefixVendor",
			"exclude_from_copy": {
				"packages": [
					"guzzlehttp/guzzle"
				]
			},
			"exclude_from_prefix": {
				"packages": [
					"guzzlehttp/guzzle"
				]
			}
		}
	}
}
```

When I install the packages (takes me ~6.5 min on M1 mac) the `woocommerce/action-scheduler` isn't in `vendor` or `vendor-prefixed` folder.

I had to exclude guzzle package from the prefixing because when I did, inside the aws-sdk-php package, in some places the guzzle classes weren't prefixed.

I'm really baffled by this tbh :/

**Comment by BrianHenryIE** [comment]
The Action Scheduler repo includes `composer.*` in its [`.gitattributes`](https://github.com/woocommerce/action-scheduler/blob/682caac422df2976dc17edb1abfe6cd2d08e2cdf/.gitattributes#L9) file, meaning it does not get downloaded and is unavailable to Strauss to process. The reason I think they do this is because they have their own code for handling multiple versions, [ActionScheduler_Versions](https://github.com/woocommerce/action-scheduler/blob/trunk/classes/ActionScheduler_Versions.php). It doesn't use namespaces and then handles loading only one version of its classes across plugins.

That said, you can force it to be prefixed using the `override_autoload` config:
```json
  "extra": {
    "strauss": {
      "override_autoload": {
        "woocommerce/action-scheduler": {
          "classmap": ["."]
        }
      }
    }
```
I've never had to include it in a plugin myself. I'd probably trust its own solution. I imagine otherwise we'd get multiple menu items for Action Scheduler and other oddities, probably database incompatibilities eventually.

What you maybe want then would be to add the `override_overload` but also include it in `exclude_from_prefix`.

What specifically was not prefixed in AWS? I did a text search for "guzzle" and at a glance, everything looks correct.

The reason it is running slow for you is that you're processing all the AWS SDK, which is huge. You probably only want one or two parts of it. I talk about it here: https://github.com/BrianHenryIE/strauss/issues/86#issuecomment-1981963868 and here's a `composer.json` that I think captures this issue minimally:

```json
{
    "name": "test/test",
    "description": "Test",
    "type": "wordpress-plugin",
    "autoload": {
        "psr-4": {
            "SomePrefix\\": [
                "src/"
            ]
        }
    },
    "require": {
        "aws/aws-sdk-php": "3.324.0",
        "woocommerce/action-scheduler": "3.7",
        "guzzlehttp/guzzle": "*"
    },
    "scripts": {
        "post-install-cmd": [
            "composer dump-autoload"
        ],
        "post-update-cmd": [
            "composer dump-autoload"
        ],
        "pre-autoload-dump": "Aws\\Script\\Composer\\Composer::removeUnusedServices"
    },
    "extra": {
        "strauss": {
            "override_autoload": {
                "woocommerce/action-scheduler": {
                    "classmap": [
                        "."
                    ]
                }
            },
            "exclude_from_prefix": {
                "packages": [
                    "woocommerce/action-scheduler"
                ]
            }
        },
        "aws/aws-sdk-php": [
            "S3"
        ]
    }
}
```

**Comment by dingo-d** [comment]
Will try this on Monday while at work, really appreciate the help 👍🏼

**Comment by dingo-d** [comment]
This works almost as it should, but guzzle is kicking me in the ass 😅 

When I didn't add it in exclusion list, I got

> action failed via WP Cron: GuzzleHttp\Client::sendAsync(): Argument # 1 ($request) must be of type Psr\Http\Message\RequestInterface, SomePrefix\GuzzleHttp\Psr7\Request given, called in .../vendor-prefixed/aws/aws-sdk-php/src/Handler/GuzzleV6/GuzzleHandler.php on line 48

When I add guzzle, psr7 and promises packages to the exclusion list I get:

> action failed via WP Cron: SomePrefix\Aws\ClientSideMonitoring\AbstractMonitoringMiddleware::__invoke(): Argument # 2 ($request) must be of type SomePrefix\Psr\Http\Message\RequestInterface, GuzzleHttp\Psr7\Request given, called in .../vendor-prefixed/aws/aws-sdk-php/src/Middleware.php on line 113

🫠 

The `removeUnusedServices` is just 🤯 You are a life-saver! 😄

**Comment by dingo-d** [comment]
Ok managed to get it workign by removing vendor, vendor-prefixed, lock file and all guzzle from strauss config and reinstalling everything 😅 

Thanks again!
