### ISSUE TITLE
Bug? Issue with composer 'static' loading

### ISSUE THREAD

**Issue by HunterNyan** [BrianHenryIE/strauss#14]
Hey, 

I'm not sure if this a bug or just not a supported functionality. I'm using strauss and it's copying over the libraries fine and generating an autoload for the classes except for the /guzzlehttp/psr7/src/functions_include.php I'm aware that this file is being deprecated but I'm just not sure if this *should* work or not.

Thanks,

**Comment by HunterNyan** [comment]
This issue does look to be the same as https://github.com/coenjacobs/mozart/issues/88

**Comment by BrianHenryIE** [comment]
Hey.

I've done that now in a branch: [Autoload](https://github.com/BrianHenryIE/strauss/tree/Autoload). I'll do some more thorough testing before merging it to master but I think it's good to go.

I also noticed a bug where `GuzzleHttp\Psr7` wasn't being prefixed because it has "psr" in it (where I had tried to fix https://github.com/coenjacobs/mozart/issues/27): https://github.com/BrianHenryIE/strauss/commit/df455ff36b5158b39b7ed728fe40608a90f01205

Thanks.

**Comment by HunterNyan** [comment]
Sweet :D 

Thank you immensely for doing this especially so fast.

**Comment by BrianHenryIE** [comment]
Should be available in 0.8.8 now. Please let me know if it causes any problems. 

I don't like how it's going to be duplicating some loading that the classmap will handle. But unless I check is each file _only_ a class, then I can't exclude it from the files autoloader.
