### ISSUE TITLE
Issue bundling AWS S3 package

### ISSUE THREAD

**Issue by kodie** [BrianHenryIE/strauss#65]
I'm attempting to bundle the [aws-sdk-php](https://github.com/aws/aws-sdk-php) package in my plugin (specifically the S3 component) and am running into an odd issue.

Basically these files:
```
vendor/aws/aws-sdk-php/src/Endpoint/UseDualstackEndpoint/Configuration.php
vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/Configuration.php
vendor/aws/aws-sdk-php/src/S3/UseArnRegion/Configuration.php
```

all have a line that looks similar to this:

```php
$this->useFipsEndpoint = Aws\boolean_value($useFipsEndpoint);
```

and after prefixing, they become something like this:

```php
$this->useFipsEndpoint = MyPlugin\Vendor\Aws\boolean_value($useFipsEndpoint);
```

Which results in this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function MyPlugin\Vendor\Aws\Endpoint\UseFipsEndpoint\MyPlugin\Vendor\Aws\boolean_value() in /app/content/plugins/my-plugin/vendor-prefixed/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/Configuration.php:20
```

If I manually add a backslash at the begining of these classes, like this:

```php
$this->useFipsEndpoint = \MyPlugin\Vendor\Aws\boolean_value($useFipsEndpoint);
```

The issue goes away and everything works as expected.

Any ideas?

**Comment by kodie** [comment]
After looking at Mozart issues, I realized that this is the exact issue I ran into while trying to use it a little over a year ago: https://github.com/coenjacobs/mozart/issues/62

**Comment by BrianHenryIE** [comment]
Oops. I haven't solved this yet.

**Comment by BrianHenryIE** [comment]
That should be fixed in master now. I'm not 100% comfortable with the solution: https://github.com/BrianHenryIE/strauss/commit/db348bbd15e6944f21f250965fa831d784afade6

In your examples, if:
```php
$this->useFipsEndpoint = Aws\boolean_value($useFipsEndpoint);
```
worked, then I would expect
```php
$this->useFipsEndpoint = MyPlugin\Vendor\Aws\boolean_value($useFipsEndpoint);
```
to also work.

My solution was to search for `MyPlugin\Vendor\Aws\boolean_value(`, i.e. namespaced function calls, and ensure there is always a leading `\`, as in your fix:

```php
$this->useFipsEndpoint = \MyPlugin\Vendor\Aws\boolean_value($useFipsEndpoint);
```

It seems safe, but since I don't understand why the original syntax _was_ working, I'm worried of unintended side effects.
