### ISSUE TITLE
Not Namespacing instanceof Statements

### ISSUE THREAD

**Issue by johnregan3** [BrianHenryIE/strauss#83]
I'm having an issue where `instanceof` statements aren't getting prefixed.  Here's an example:

```
public static function _apply_endpoint_provider($value, array &$args)
    {
        if (!isset($args['endpoint'])) {
            if ($value instanceof \Aws\EndpointV2\EndpointProviderV2) {
                $options = self::getEndpointProviderOptions($args);
                $value = PartitionEndpointProvider::defaultProvider($options)
                    ->getPartition($args['region'], $args['service']);
            }
...
```

All of the `use` statements at the top of the Class are namespaced appropriately.

I'm using v0.15.0.  Here's the relevant part of my config:
```
	"extra": {
		"strauss": {
			"target_directory": "vendor-prefixed",
			"namespace_prefix": "John_Regan\\Strauss",
			"packages": [
				"aws/aws-sdk-php"
			],
			"include_modified_date": false,
			"include_author": false
		}
	}
```

Thanks for the work on this. It's a fantastic tool!

**Comment by BrianHenryIE** [comment]
Fixed in master https://github.com/BrianHenryIE/strauss/commit/67f471ab47fe9025e040ab0116f03b410bfbb7dc

There's a bit of a breaking change in master you might not want to deal with yet, https://github.com/BrianHenryIE/strauss/commit/1bd20b75a4e6b5c07a428c04e8b9e514034b6b5c, where it deals with polyfills. Previously it was picking up PHP classes which were defined in polyfill packages and prefixing their use throughout the code. But the polyfill packages may be conditionally loading the class based on PHP version, so then the class _only_ exists on older PHP versions. I think this new approach – _do not_ prefix built-in PHP classes – is correct. It still leaves the potential collision where a polyfill can be loaded in two different plugins and may try to define the class twice – if the polyfill checks based on PHP version, it will be a problem, if it checks based on `class_exists` it should be safe.

You can add `.patch` to any commit or PR on Github and use [cweagans/composer-patches](https://github.com/cweagans/composer-patches) to apply it: https://github.com/BrianHenryIE/strauss/commit/67f471ab47fe9025e040ab0116f03b410bfbb7dc.patch

**Comment by johnregan3** [comment]
@BrianHenryIE Thanks!  You're the best!
